apiVersion: build.pivotal.io/v1alpha1
kind: Image
metadata:
  name: kpack-dotnet-image
spec:
  tag: ddieruf/kpack-demo-dotnet
  serviceAccount: docker-service-account
  cacheSize: "1.5Gi"
  builder:
    name: cloud-foundry
    kind: ClusterBuilder
  source:
    git:
      url: https://github.com/ddieruf/kpack-demo
      revision: master